In [ ]:
import pandas as pd
import numpy as np
ds=pd.Series([10,20,30,40])
ds

0    10
1    20
2    30
3    40
dtype: int64

In [4]:
import pandas as pd
import numpy as np
ds=pd.Series((10,20,30,40))
ds

0    10
1    20
2    30
3    40
dtype: int64

In [6]:
import pandas as pd
import numpy as np
ds=pd.Series([10,20,30,40],index=['A','B','C','D'])
ds

A    10
B    20
C    30
D    40
dtype: int64

In [8]:
import pandas as pd
import numpy as np
ds=pd.Series({'S':10,'A':20,'M':30})
ds

S    10
A    20
M    30
dtype: int64

In [10]:
import pandas as pd
import numpy as np
ds=pd.Series(range(1,10))
ds

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int64

In [12]:
import pandas as pd
import numpy as np
ds=pd.Series(np.array([10,20,30]))
ds

0    10
1    20
2    30
dtype: int32

In [14]:
type(ds)

pandas.core.series.Series

In [17]:
import pandas as pd
import numpy as np
ds=pd.DataFrame([['S','A','M'],[10,20,30],[1,2,3]],index=['A','B','C'],columns=['P','Q','R'])
ds

    P   Q   R
A   S   A   M
B  10  20  30
C   1   2   3

In [19]:
import pandas as pd
import numpy as np
ds=pd.DataFrame({'P':['S','A','M'],'Q':[10,20,30],'R':[1,2,3]},index=['A','B','C'])
ds

   P   Q  R
A  S  10  1
B  A  20  2
C  M  30  3

In [20]:
import pandas as pd
import numpy as np
ds=pd.DataFrame({'P':['S','A','M'],'Q':[10,20,30],'R':[1,2,3]},index=['A','B','C'],columns=['X','Y','Z'])
ds

     X    Y    Z
A  NaN  NaN  NaN
B  NaN  NaN  NaN
C  NaN  NaN  NaN

In [22]:
import pandas as pd
import numpy as np
ds=pd.DataFrame(np.array([['S','A','M'],[10,20,30],[1,2,3]]),index=['A','B','C'],columns=['P','Q','R'])
ds

    P   Q   R
A   S   A   M
B  10  20  30
C   1   2   3

In [48]:
import pandas as pd
import numpy as np
df=pd.DataFrame({'Sub':['Python','FSD','COA','TOC','DM'],'Fac':['VHA','PSP','VBY','DPS','MSS'],'Mark':[10,9,10,9,9]})
df

      Sub  Fac  Mark
0  Python  VHA    10
1     FSD  PSP     9
2     COA  VBY    10
3     TOC  DPS     9
4      DM  MSS     9

In [49]:
ds.set_index('Sub')

        Fac  Mark
Sub
Python  VHA    10
FSD     PSP     9
COA     VBY    10
TOC     DPS     9
DM      MSS     9

In [50]:
df.set_index('Sub',drop=True)

        Fac  Mark
Sub
Python  VHA    10
FSD     PSP     9
COA     VBY    10
TOC     DPS     9
DM      MSS     9

In [51]:
df.set_index('Sub',drop=False)

           Sub  Fac  Mark
Sub
Python  Python  VHA    10
FSD        FSD  PSP     9
COA        COA  VBY    10
TOC        TOC  DPS     9
DM          DM  MSS     9

In [52]:
df=df.set_index('Sub',drop=True)
df

        Fac  Mark
Sub
Python  VHA    10
FSD     PSP     9
COA     VBY    10
TOC     DPS     9
DM      MSS     9

In [53]:
df=df.reset_index()
df

      Sub  Fac  Mark
0  Python  VHA    10
1     FSD  PSP     9
2     COA  VBY    10
3     TOC  DPS     9
4      DM  MSS     9

In [54]:
df=df.reset_index()
df

   index     Sub  Fac  Mark
0      0  Python  VHA    10
1      1     FSD  PSP     9
2      2     COA  VBY    10
3      3     TOC  DPS     9
4      4      DM  MSS     9

In [57]:
df=df.set_index('index')

In [58]:
df

          Sub  Fac  Mark
index
0      Python  VHA    10
1         FSD  PSP     9
2         COA  VBY    10
3         TOC  DPS     9
4          DM  MSS     9

In [59]:
df=df.set_index('Sub')

In [60]:
df

        Fac  Mark
Sub
Python  VHA    10
FSD     PSP     9
COA     VBY    10
TOC     DPS     9
DM      MSS     9

In [62]:
df.loc['FSD','Fac']='NAS'

In [63]:
df

        Fac  Mark
Sub
Python  VHA    10
FSD     NAS     9
COA     VBY    10
TOC     DPS     9
DM      MSS     9

In [65]:
df.loc['FSD','Mark']=10

In [66]:
df

        Fac  Mark
Sub
Python  VHA    10
FSD     NAS    10
COA     VBY    10
TOC     DPS     9
DM      MSS     9

In [67]:
df.loc['Project']=['VHA',10]

In [68]:
df

         Fac  Mark
Sub
Python   VHA    10
FSD      NAS    10
COA      VBY    10
TOC      DPS     9
DM       MSS     9
Project  VHA    10

In [69]:
df['HOD']='MJT'

In [70]:
df

         Fac  Mark  HOD
Sub
Python   VHA    10  MJT
FSD      NAS    10  MJT
COA      VBY    10  MJT
TOC      DPS     9  MJT
DM       MSS     9  MJT
Project  VHA    10  MJT

In [71]:
df['New']=df['Mark']*10

In [72]:
df

         Fac  Mark  HOD  New
Sub
Python   VHA    10  MJT  100
FSD      NAS    10  MJT  100
COA      VBY    10  MJT  100
TOC      DPS     9  MJT   90
DM       MSS     9  MJT   90
Project  VHA    10  MJT  100

In [96]:
import pandas as pd
import numpy as np
ds=pd.DataFrame((np.random.randint(1,100,(8,5))),columns=['A','B','C','D','E'])

In [97]:
print(ds)
ds['Sum']=ds['A']+ds['B']+ds['C']+ds['D']+ds['E']

    A   B   C   D   E
0  11  62  94  21  42
1  91  24  60  84  45
2  49  24  70  73  78
3  43  87  11  18  56
4  22  33  83  75  98
5  58  13  53  52  67
6  58  22  65  38  88
7  54  96  54  55   2

In [ ]:
print(ds.shape)

(8, 6)

In [99]:
print(ds.size)

48

In [100]:
print(ds.ndim)

2

In [101]:
print(ds)

    A   B   C   D   E  Sum
0  11  62  94  21  42  230
1  91  24  60  84  45  304
2  49  24  70  73  78  294
3  43  87  11  18  56  215
4  22  33  83  75  98  311
5  58  13  53  52  67  243
6  58  22  65  38  88  271
7  54  96  54  55   2  261

In [102]:
ds.iloc[6,2]=36
ds

    A   B   C   D   E  Sum
0  11  62  94  21  42  230
1  91  24  60  84  45  304
2  49  24  70  73  78  294
3  43  87  11  18  56  215
4  22  33  83  75  98  311
5  58  13  53  52  67  243
6  58  22  36  38  88  271
7  54  96  54  55   2  261

In [103]:
ds.loc[2:7,'B':'D']

    B   C   D
2  24  70  73
3  87  11  18
4  33  83  75
5  13  53  52
6  22  36  38
7  96  54  55

In [104]:
ds.loc[9]=[50,70,80,90,100,1]
ds

    A   B   C   D    E  Sum
0  11  62  94  21   42  230
1  91  24  60  84   45  304
2  49  24  70  73   78  294
3  43  87  11  18   56  215
4  22  33  83  75   98  311
5  58  13  53  52   67  243
6  58  22  36  38   88  271
7  54  96  54  55    2  261
9  50  70  80  90  100    1

In [119]:
df=pd.DataFrame({'CourseID':[1,2,3,4,5],'CourseName':['Python','FSD','COA','TOC','DM'],'Credits':[6,6,4,5,5],'Faculty':['VHA','PSP','VBY','DPS','MSS']})
df

   CourseID CourseName  Credits Faculty
0         1     Python        6     VHA
1         2        FSD        6     PSP
2         3        COA        4     VBY
3         4        TOC        5     DPS
4         5         DM        5     MSS

In [123]:
df=df.set_index('CourseID')

In [124]:
df['Semester']=1

In [125]:
df

         CourseName  Credits Faculty  Semester
CourseID
1            Python        6     VHA         1
2               FSD        6     PSP         1
3               COA        4     VBY         1
4               TOC        5     DPS         1
5                DM        5     MSS         1

In [126]:
df.iloc[1,1]=7

In [127]:
df

         CourseName  Credits Faculty  Semester
CourseID
1            Python        6     VHA         1
2               FSD        7     PSP         1
3               COA        4     VBY         1
4               TOC        5     DPS         1
5                DM        5     MSS         1

In [1]:
df['Project']=['semIV',7,'VHA',1]

NameError: name 'df' is not defined

In [130]:
df

         CourseName  Credits Faculty  Semester
CourseID
1            Python        6     VHA         1
2               FSD        7     PSP         1
3               COA        4     VBY         1
4               TOC        5     DPS         1
5                DM        5     MSS         1
Project       semIV        7     VHA         1