In [1]:
import pandas as pd
import numpy as np

In [4]:
df=pd.Series([1,2,3,4,5])
df.reset_index()

   index  0
0      0  1
1      1  2
2      2  3
3      3  4
4      4  5

In [17]:
df=pd.DataFrame([["Fsd","PP",23],['python','vha',22],['coa','vvv',20]],
          index=[1,2,3],columns=['subject','faculty','marks'])

In [18]:
df

  subject faculty  marks
1     Fsd      PP     23
2  python     vha     22
3     coa     vvv     20

In [23]:
df=df.set_index('subject',drop=False)

In [27]:
df=df.reset_index(drop=True)

In [28]:
df

  subject faculty  marks
0     Fsd      PP     23
1  python     vha     22
2     coa     vvv     20

In [ ]:
df.loc[1,'faculty':'marks'] = ['prp','24']

C:\Users\zaid\AppData\Local\Temp\ipykernel_47764\1914590606.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '24' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[1,'faculty':'marks'] = ['prp','24']

In [38]:
df

  subject faculty marks
0     Fsd      PP    23
1  python     prp    24
2     coa     vvv    20

In [39]:
df.loc[3]=['project','psp',20]

In [40]:
df

   subject faculty marks
0      Fsd      PP    23
1   python     prp    24
2      coa     vvv    20
3  project     psp    20

In [42]:
df['hod']='mjt'

In [43]:
df

   subject faculty marks  hod
0      Fsd      PP    23  mjt
1   python     prp    24  mjt
2      coa     vvv    20  mjt
3  project     psp    20  mjt

In [20]:
import pandas as pd

df = pd.DataFrame({
    "city": ["NY", "NY", "LA", "LA", "LA"],
    "category": ["A", "B", "A", "A", "B"],
    "sales": [100, 200, 50, 70, 30],
    "units": [1, 3, 1, 2, 2],
    "date": pd.to_datetime(["2026-01-01","2026-01-02","2026-01-01","2026-01-03","2026-01-04"])
})
df

  city category  sales  units       date
0   NY        A    100      1 2026-01-01
1   NY        B    200      3 2026-01-02
2   LA        A     50      1 2026-01-01
3   LA        A     70      2 2026-01-03
4   LA        B     30      2 2026-01-04

In [21]:
df.groupby('city')['sales'].count()

city
LA    3
NY    2
Name: sales, dtype: int64

In [22]:
df.groupby(['city','category'],as_index=False)['sales'].count()

  city category  sales
0   LA        A      2
1   LA        B      1
2   NY        A      1
3   NY        B      1

In [23]:
df.groupby("city")[["sales", "units"]].sum()

      sales  units
city
LA      150      5
NY      300      4

In [24]:
df.groupby('city').agg({'sales':['sum','max'],'units':['sum','max']})

     sales      units
       sum  max   sum max
city
LA     150   70     5   2
NY     300  200     4   3

In [25]:
out = df.groupby("city").agg(
    total_sales=("sales", "sum"),
    avg_sales=("sales", "mean"),
    total_units=("units", "sum"),
    n_orders=("sales", "size")
).reset_index()
out

  city  total_sales  avg_sales  total_units  n_orders
0   LA          150       50.0            5         3
1   NY          300      150.0            4         2

In [37]:
df.groupby('city').filter(lambda x: x['sales'].sum()>100)

  city category  sales  units       date
0   NY        A    100      1 2026-01-01
1   NY        B    200      3 2026-01-02
2   LA        A     50      1 2026-01-01
3   LA        A     70      2 2026-01-03
4   LA        B     30      2 2026-01-04

In [38]:
df["city_avg_sales"] = df.groupby("city")["sales"].transform("mean")

In [49]:
df.groupby('city').filter(lambda x: x['sales'].sum() > 150)

  city category  sales  units       date  city_avg_sales
0   NY        A    100      1 2026-01-01           150.0
1   NY        B    200      3 2026-01-02           150.0

In [46]:
df

  city category  sales  units       date  city_avg_sales
0   NY        A    100      1 2026-01-01           150.0
1   NY        B    200      3 2026-01-02           150.0
2   LA        A     50      1 2026-01-01            50.0
3   LA        A     70      2 2026-01-03            50.0
4   LA        B     30      2 2026-01-04            50.0

In [51]:
df["city_sales_share"] = df["sales"] / df.groupby("city")["sales"].transform("sum")
df

  city category  sales  units       date  city_avg_sales  city_sales_share
0   NY        A    100      1 2026-01-01           150.0          0.333333
1   NY        B    200      3 2026-01-02           150.0          0.666667
2   LA        A     50      1 2026-01-01            50.0          0.333333
3   LA        A     70      2 2026-01-03            50.0          0.466667
4   LA        B     30      2 2026-01-04            50.0          0.200000