In [3]:
import pandas as pd
import numpy as np
df=pd.read_csv("IPL_Matches_2008_2022.csv")
df.head()

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan

In [4]:
df.columns

Index(['ID', 'City', 'Date', 'Season', 'MatchNumber', 'Team1', 'Team2',
       'Venue', 'TossWinner', 'TossDecision', 'SuperOver', 'WinningTeam',
       'WonBy', 'Margin', 'method', 'Player_of_Match', 'Team1Players',
       'Team2Players', 'Umpire1', 'Umpire2'],
      dtype='object')

In [13]:
df[(df['WinningTeam'].eq('Gujarat Titans')) & (df['SuperOver'].eq('Y'))]

Empty DataFrame
Columns: [ID, City, Date, Season, MatchNumber, Team1, Team2, Venue, TossWinner, TossDecision, SuperOver, WinningTeam, WonBy, Margin, method, Player_of_Match, Team1Players, Team2Players, Umpire1, Umpire2]
Index: []

In [16]:
df[df['WinningTeam']==df['TossWinner']].shape[0]

489

In [12]:
def most_common_player(g):
    return g["Player_of_Match"].value_counts().head(1)

out = df.groupby("Venue").apply(most_common_player)
out

C:\Users\zaid\AppData\Local\Temp\ipykernel_18264\4086993232.py:4: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  out = df.groupby("Venue").apply(most_common_player)

Venue                                                 Player_of_Match
Arun Jaitley Stadium                                  A Mishra           2
Arun Jaitley Stadium, Delhi                           JC Buttler         1
Barabati Stadium                                      A Symonds          2
Brabourne Stadium                                     SR Watson          1
Brabourne Stadium, Mumbai                             Kuldeep Yadav      3
Buffalo Park                                          A Nehra            1
De Beers Diamond Oval                                 DR Smith           1
Dr DY Patil Sports Academy                            YK Pathan          2
Dr DY Patil Sports Academy, Mumbai                    Q de Kock          2
Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium   F du Plessis       1
Dubai International Cricket Stadium                   RD Gaikwad         4
Eden Gardens                                          AD Russell         8
Eden Gardens, Kolkata                                 RM Patidar         1
Feroz Shah Kotla                                      DA Warner          3
Green Park                                            Mohammed Siraj     1
Himachal Pradesh Cricket Association Stadium          AC Gilchrist       2
Holkar Cricket Stadium                                UT Yadav           1
JSCA International Stadium Complex                    RA Jadeja          2
Kingsmead                                             M Muralitharan     1
M Chinnaswamy Stadium                                 CH Gayle           9
M.Chinnaswamy Stadium                                 AB de Villiers     3
MA Chidambaram Stadium                                MS Dhoni           2
MA Chidambaram Stadium, Chepauk                       MEK Hussey         5
MA Chidambaram Stadium, Chepauk, Chennai              PP Shaw            1
Maharashtra Cricket Association Stadium               AB de Villiers     2
Maharashtra Cricket Association Stadium, Pune         AD Russell         1
Narendra Modi Stadium, Ahmedabad                      HH Pandya          1
Nehru Stadium                                         BJ Hodge           1
New Wanderers Stadium                                 JH Kallis          2
Newlands                                              KC Sangakkara      1
OUTsurance Oval                                       AB de Villiers     1
Punjab Cricket Association IS Bindra Stadium          KL Rahul           3
Punjab Cricket Association IS Bindra Stadium, Mohali  MM Sharma          1
Punjab Cricket Association Stadium, Mohali            SE Marsh           5
Rajiv Gandhi International Stadium                    Rashid Khan        3
Rajiv Gandhi International Stadium, Uppal             DA Warner          7
Sardar Patel Stadium, Motera                          AM Rahane          2
Saurashtra Cricket Association Stadium                KH Pandya          1
Sawai Mansingh Stadium                                AM Rahane          4
Shaheed Veer Narayan Singh International Stadium      DA Warner          2
Sharjah Cricket Stadium                               GJ Maxwell         3
Sheikh Zayed Stadium                                  BA Stokes          2
St George's Park                                      ML Hayden          1
Subrata Roy Sahara Stadium                            LJ Wright          1
SuperSport Park                                       AC Gilchrist       1
Vidarbha Cricket Association Stadium, Jamtha          Harmeet Singh      1
Wankhede Stadium                                      RG Sharma          7
Wankhede Stadium, Mumbai                              S Dhawan           3
Zayed Cricket Stadium, Abu Dhabi                      Ishan Kishan       1
Name: count, dtype: int64

### Season wise team won the matches max

In [27]:
df.groupby('Season')['WinningTeam'].apply(lambda x:x.value_counts().head(1)).reset_index()

     Season                level_1  WinningTeam
0   2007/08       Rajasthan Royals           13
1      2009       Delhi Daredevils           10
2   2009/10         Mumbai Indians           11
3      2011    Chennai Super Kings           11
4      2012  Kolkata Knight Riders           12
5      2013         Mumbai Indians           13
6      2014        Kings XI Punjab           12
7      2015         Mumbai Indians           10
8      2016    Sunrisers Hyderabad           11
9      2017         Mumbai Indians           12
10     2018    Chennai Super Kings           11
11     2019         Mumbai Indians           11
12  2020/21         Mumbai Indians           11
13     2021    Chennai Super Kings           11
14     2022         Gujarat Titans           12

In [31]:
df.groupby('Season')['WinningTeam'].apply(lambda x:x.value_counts().head(1))

Season
2007/08  Rajasthan Royals         13
2009     Delhi Daredevils         10
2009/10  Mumbai Indians           11
2011     Chennai Super Kings      11
2012     Kolkata Knight Riders    12
2013     Mumbai Indians           13
2014     Kings XI Punjab          12
2015     Mumbai Indians           10
2016     Sunrisers Hyderabad      11
2017     Mumbai Indians           12
2018     Chennai Super Kings      11
2019     Mumbai Indians           11
2020/21  Mumbai Indians           11
2021     Chennai Super Kings      11
2022     Gujarat Titans           12
Name: WinningTeam, dtype: int64

### Nuumber of the unique player man of the match of each winning team in descending order

In [ ]:
df.groupby("WinningTeam")['Player_of_Match'].apply(lambda x:x.nunique()).sort_values(ascending=False).reset_index()

###  Which team wins the maximum for the individual stadium

In [56]:
wins = (
    df.dropna(subset=["WinningTeam"])
      .groupby(["Venue", "WinningTeam"])
      .size()
      .reset_index(name="wins")
)
venue_max_one = (
    wins.sort_values(["Venue", "wins", "WinningTeam"], ascending=[True, False, True])
        .groupby("Venue", as_index=False)
        .head(1)
)

venue_max_one.head(5)

                          Venue      WinningTeam  wins
1          Arun Jaitley Stadium   Delhi Capitals     4
8   Arun Jaitley Stadium, Delhi   Mumbai Indians     2
10             Barabati Stadium  Deccan Chargers     3
14            Brabourne Stadium   Mumbai Indians     5
18    Brabourne Stadium, Mumbai   Delhi Capitals     4

In [54]:
def individual_wins(g):
    return 0
df.groupby('Venue')['WinningTeam'].apply(lambda x:x.value_counts().head(1)).reset_index().head(5)

                         Venue                level_1  WinningTeam
0         Arun Jaitley Stadium         Delhi Capitals            4
1  Arun Jaitley Stadium, Delhi         Mumbai Indians            2
2             Barabati Stadium  Kolkata Knight Riders            3
3            Brabourne Stadium         Mumbai Indians            5
4    Brabourne Stadium, Mumbai         Delhi Capitals            4

In [53]:
new_df=pd.DataFrame()
new_df["Count"]=df.Venue.value_counts().head(5)

In [47]:
new_df=new_df.reset_index()
new_df

                                       Venue  Count
0                               Eden Gardens     77
1                           Wankhede Stadium     73
2                      M Chinnaswamy Stadium     65
3                           Feroz Shah Kotla     60
4  Rajiv Gandhi International Stadium, Uppal     49

In [49]:
df1=new_df.merge(df,on="Venue",how="inner")

In [50]:
df1

,Venue,Count,ID,City,Date,Season,MatchNumber,Team1,Team2,TossWinner,...,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,Eden Gardens,77,1178422,Kolkata,2019-04-28,2019,47,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,...,N,Kolkata Knight Riders,Runs,34.0,NaN,AD Russell,"['Shubman Gill', 'CA Lynn', 'AD Russell', 'KD ...","['Q de Kock', 'RG Sharma', 'E Lewis', 'SA Yada...",IJ Gould,Nitin Menon
1,Eden Gardens,77,1178418,Kolkata,2019-04-25,2019,43,Kolkata Knight Riders,Rajasthan Royals,Rajasthan Royals,...,N,Rajasthan Royals,Wickets,3.0,NaN,VR Aaron,"['CA Lynn', 'Shubman Gill', 'N Rana', 'KD Kart...","['AM Rahane', 'SV Samson', 'SPD Smith', 'BA St...",AY Dandekar,IJ Gould
2,Eden Gardens,77,1178410,Kolkata,2019-04-19,2019,35,Royal Challengers Bangalore,Kolkata Knight Riders,Kolkata Knight Riders,...,N,Royal Challengers Bangalore,Runs,10.0,NaN,V Kohli,"['PA Patel', 'V Kohli', 'AD Nath', 'MM Ali', '...","['CA Lynn', 'SP Narine', 'Shubman Gill', 'RV U...",IJ Gould,Nitin Menon
3,Eden Gardens,77,1178404,Kolkata,2019-04-14,2019,29,Kolkata Knight Riders,Chennai Super Kings,Chennai Super Kings,...,N,Chennai Super Kings,Wickets,5.0,NaN,Imran Tahir,"['CA Lynn', 'SP Narine', 'N Rana', 'RV Uthappa...","['SR Watson', 'F du Plessis', 'SK Raina', 'AT ...",CK Nandan,RJ Tucker
4,Eden Gardens,77,1178401,Kolkata,2019-04-12,2019,26,Kolkata Knight Riders,Delhi Capitals,Delhi Capitals,...,N,Delhi Capitals,Wickets,7.0,NaN,S Dhawan,"['JL Denly', 'Shubman Gill', 'RV Uthappa', 'N ...","['PP Shaw', 'S Dhawan', 'SS Iyer', 'RR Pant', ...",CK Nandan,YC Barde
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319,"Rajiv Gandhi International Stadium, Uppal",49,336024,Hyderabad,2008-05-18,2007/08,42,Deccan Chargers,Mumbai Indians,Deccan Chargers,...,N,Mumbai Indians,Runs,25.0,NaN,DJ Bravo,"['AC Gilchrist', 'Shahid Afridi', 'RG Sharma',...","['ST Jayasuriya', 'SR Tendulkar', 'DJ Thornely...",BR Doctrove,DJ Harper
320,"Rajiv Gandhi International Stadium, Uppal",49,336014,Hyderabad,2008-05-11,2007/08,32,Deccan Chargers,Kolkata Knight Riders,Kolkata Knight Riders,...,N,Kolkata Knight Riders,Runs,23.0,NaN,SC Ganguly,"['AC Gilchrist', 'HH Gibbs', 'DB Ravi Teja', '...","['Salman Butt', 'A Chopra', 'SC Ganguly', 'DJ ...",IL Howell,AM Saheba
321,"Rajiv Gandhi International Stadium, Uppal",49,335999,Hyderabad,2008-05-01,2007/08,19,Deccan Chargers,Kings XI Punjab,Kings XI Punjab,...,N,Kings XI Punjab,Wickets,7.0,NaN,SE Marsh,"['AC Gilchrist', 'VVS Laxman', 'HH Gibbs', 'RG...","['SE Marsh', 'RR Sarwan', 'KC Sangakkara', 'Yu...",BR Doctrove,RB Tiffin
322,"Rajiv Gandhi International Stadium, Uppal",49,335990,Hyderabad,2008-04-24,2007/08,9,Deccan Chargers,Rajasthan Royals,Rajasthan Royals,...,N,Rajasthan Royals,Wickets,3.0,NaN,YK Pathan,"['AC Gilchrist', 'VVS Laxman', 'Shahid Afridi'...","['Kamran Akmal', 'GC Smith', 'YK Pathan', 'SR ...",Asad Rauf,MR Benson
323,"Rajiv Gandhi International Stadium, Uppal",49,335988,Hyderabad,2008-04-22,2007/08,7,Deccan Chargers,Delhi Daredevils,Deccan Chargers,...,N,Delhi Daredevils,Wickets,9.0,NaN,V Sehwag,"['AC Gilchrist', 'Y Venugopal Rao', 'VVS Laxma...","['G Gambhir', 'V Sehwag', 'S Dhawan', 'Shoaib ...",IL Howell,AM Saheba

In [51]:
df1.groupby("Venue")["WinningTeam"].apply(lambda x:x.value_counts().head(1)).reset_index()

,Venue,level_1,WinningTeam
0,Eden Gardens,Kolkata Knight Riders,45
1,Feroz Shah Kotla,Delhi Daredevils,23
2,M Chinnaswamy Stadium,Royal Challengers Bangalore,29
3,"Rajiv Gandhi International Stadium, Uppal",Sunrisers Hyderabad,20
4,Wankhede Stadium,Mumbai Indians,42

 ### Season wise point Table;2 point for winner else 1 point

In [57]:
import pandas as pd

matches = pd.read_csv("IPL_Matches_2008_2022.csv")

def matches_played(df, team):
    return df[(df.Team1 == team) | (df.Team2 == team)].shape[0]

def matches_won(df, team):
    return df[df.WinningTeam == team].shape[0]

def matches_no_result(df, team):
    return df[((df.Team1 == team) | (df.Team2 == team)) & (df.WinningTeam.isnull())].shape[0]

def point_table(season):
    df = matches[matches.Season == season]
    new_df = pd.DataFrame()
    new_df['Team Name'] = df.Team1.unique()
    
    new_df["Matches Played"] = new_df["Team Name"].apply(lambda x: matches_played(df, x))
    new_df["Matches Won"] = new_df["Team Name"].apply(lambda x: matches_won(df, x))
    new_df["No Result"] = new_df["Team Name"].apply(lambda x: matches_no_result(df, x))
    
    new_df["Points"] = new_df["Matches Won"]*2 + new_df["No Result"]
    
    new_df.sort_values("Points", ascending=False, inplace=True)
    new_df.set_index("Team Name", inplace=True)
    
    return new_df

#  Apply for all seasons
all_seasons = {}

for season in matches.Season.unique():
    all_seasons[season] = point_table(season)

# Example: print all
for season in all_seasons:
    print("\nSeason:", season)
    print(all_seasons[season])

Season: 2022
                             Matches Played  Matches Won  No Result  Points
Team Name
Gujarat Titans                           16           12          0      24
Rajasthan Royals                         17           10          0      20
Royal Challengers Bangalore              16            9          0      18
Lucknow Super Giants                     15            9          0      18
Punjab Kings                             14            7          0      14
Delhi Capitals                           14            7          0      14
Kolkata Knight Riders                    14            6          0      12
Sunrisers Hyderabad                      14            6          0      12
Chennai Super Kings                      14            4          0       8
Mumbai Indians                           14            4          0       8

Season: 2021
                             Matches Played  Matches Won  No Result  Points
Team Name
Chennai Super Kings                      16           11          0      22
Delhi Capitals                           16           10          0      20
Royal Challengers Bangalore              15            9          0      18
Kolkata Knight Riders                    17            9          0      18
Mumbai Indians                           14            7          0      14
Punjab Kings                             14            6          0      12
Rajasthan Royals                         14            5          0      10
Sunrisers Hyderabad                      14            3          0       6

Season: 2020/21
                             Matches Played  Matches Won  No Result  Points
Team Name
Mumbai Indians                           16           11          0      22
Delhi Capitals                           17            9          0      18
Sunrisers Hyderabad                      16            8          0      16
Royal Challengers Bangalore              15            7          0      14
Kolkata Knight Riders                    14            7          0      14
Kings XI Punjab                          14            6          0      12
Chennai Super Kings                      14            6          0      12
Rajasthan Royals                         14            6          0      12

Season: 2019
                             Matches Played  Matches Won  No Result  Points
Team Name
Mumbai Indians                           16           11          0      22
Delhi Capitals                           16           10          0      20
Chennai Super Kings                      17           10          0      20
Sunrisers Hyderabad                      15            6          0      12
Kolkata Knight Riders                    14            6          0      12
Kings XI Punjab                          14            6          0      12
Rajasthan Royals                         14            5          1      11
Royal Challengers Bangalore              14            5          1      11

Season: 2018
                             Matches Played  Matches Won  No Result  Points
Team Name
Chennai Super Kings                      16           11          0      22
Sunrisers Hyderabad                      17           10          0      20
Kolkata Knight Riders                    16            9          0      18
Rajasthan Royals                         15            7          0      14
Royal Challengers Bangalore              14            6          0      12
Kings XI Punjab                          14            6          0      12
Mumbai Indians                           14            6          0      12
Delhi Daredevils                         14            5          0      10

Season: 2017
                             Matches Played  Matches Won  No Result  Points
Team Name
Mumbai Indians                           17           12          0      24
Rising Pune Supergiant                   16           10          0      20
Kolkata Knight Riders                    16            9          0      18
Sunrisers Hyderabad                      14            8          0      16
Kings XI Punjab                          14            7          0      14
Delhi Daredevils                         14            6          0      12
Gujarat Lions                            14            4          0       8
Royal Challengers Bangalore              13            3          0       6

Season: 2016
                             Matches Played  Matches Won  No Result  Points
Team Name
Sunrisers Hyderabad                      17           11          0      22
Royal Challengers Bangalore              16            9          0      18
Gujarat Lions                            16            9          0      18
Kolkata Knight Riders                    15            8          0      16
Delhi Daredevils                         14            7          0      14
Mumbai Indians                           14            7          0      14
Rising Pune Supergiants                  14            5          0      10
Kings XI Punjab                          14            4          0       8

Season: 2015
                             Matches Played  Matches Won  No Result  Points
Team Name
Mumbai Indians                           16           10          0      20
Chennai Super Kings                      17           10          0      20
Royal Challengers Bangalore              16            8          2      18
Rajasthan Royals                         14            7          1      15
Sunrisers Hyderabad                      14            7          0      14
Kolkata Knight Riders                    13            7          0      14
Delhi Daredevils                         14            5          1      11
Kings XI Punjab                          14            3          0       6

Season: 2014
                             Matches Played  Matches Won  No Result  Points
Team Name
Kings XI Punjab                          17           12          0      24
Kolkata Knight Riders                    16           11          0      22
Chennai Super Kings                      16           10          0      20
Mumbai Indians                           15            7          0      14
Rajasthan Royals                         14            7          0      14
Sunrisers Hyderabad                      14            6          0      12
Royal Challengers Bangalore              14            5          0      10
Delhi Daredevils                         14            2          0       4

Season: 2013
                             Matches Played  Matches Won  No Result  Points
Team Name
Mumbai Indians                           19           13          0      26
Chennai Super Kings                      18           12          0      24
Rajasthan Royals                         18           11          0      22
Sunrisers Hyderabad                      17           10          0      20
Royal Challengers Bangalore              16            9          0      18
Kings XI Punjab                          16            8          0      16
Kolkata Knight Riders                    16            6          0      12
Pune Warriors                            16            4          0       8
Delhi Daredevils                         16            3          0       6

Season: 2012
                             Matches Played  Matches Won  No Result  Points
Team Name
Kolkata Knight Riders                    17           12          0      24
Delhi Daredevils                         18           11          0      22
Chennai Super Kings                      18           10          0      20
Mumbai Indians                           17           10          0      20
Kings XI Punjab                          16            8          0      16
Royal Challengers Bangalore              15            8          0      16
Rajasthan Royals                         16            7          0      14
Deccan Chargers                          15            4          0       8
Pune Warriors                            16            4          0       8

Season: 2011
                             Matches Played  Matches Won  No Result  Points
Team Name
Chennai Super Kings                      16           11          0      22
Royal Challengers Bangalore              16           10          0      20
Mumbai Indians                           16           10          0      20
Kolkata Knight Riders                    15            8          0      16
Kings XI Punjab                          14            7          0      14
Kochi Tuskers Kerala                     14            6          0      12
Deccan Chargers                          14            6          0      12
Rajasthan Royals                         13            6          0      12
Delhi Daredevils                         14            4          1       9
Pune Warriors                            14            4          1       9

Season: 2009/10
                             Matches Played  Matches Won  No Result  Points
Team Name
Mumbai Indians                           16           11          0      22
Chennai Super Kings                      16            9          0      18
Deccan Chargers                          16            8          0      16
Royal Challengers Bangalore              16            8          0      16
Delhi Daredevils                         14            7          0      14
Kolkata Knight Riders                    14            7          0      14
Rajasthan Royals                         14            6          0      12
Kings XI Punjab                          14            4          0       8

Season: 2009
                             Matches Played  Matches Won  No Result  Points
Team Name
Delhi Daredevils                         15           10          0      20
Royal Challengers Bangalore              16            9          0      18
Deccan Chargers                          16            9          0      18
Chennai Super Kings                      14            8          0      16
Kings XI Punjab                          14            7          0      14
Mumbai Indians                           13            5          0      10
Kolkata Knight Riders                    13            3          0       6

Season: 2007/08
                             Matches Played  Matches Won  No Result  Points
Team Name
Rajasthan Royals                         16           13          0      26
Kings XI Punjab                          15           10          0      20
Chennai Super Kings                      16            9          0      18
Delhi Daredevils                         14            7          0      14
Mumbai Indians                           14            7          0      14
Kolkata Knight Riders                    13            6          0      12
Royal Challengers Bangalore              14            4          0       8
Deccan Chargers                          14            2          0       4