In [48]:
import pandas as pd
import numpy as np

In [49]:
df=pd.DataFrame([[1,np.nan,3,4],[2,4,np.nan,8],[np.nan,4,5,9],
                 [np.nan,1,np.nan,3],[np.nan,np.nan,np.nan,np.nan],[1,1,1,1]],columns=["A","B","C","D"])

In [50]:
df

     A    B    C    D
0  1.0  NaN  3.0  4.0
1  2.0  4.0  NaN  8.0
2  NaN  4.0  5.0  9.0
3  NaN  1.0  NaN  3.0
4  NaN  NaN  NaN  NaN
5  1.0  1.0  1.0  1.0

In [51]:
df.isna()

       A      B      C      D
0  False   True  False  False
1  False  False   True  False
2   True  False  False  False
3   True  False   True  False
4   True   True   True   True
5  False  False  False  False

In [52]:
df.isna().sum()

A    3
B    2
C    3
D    1
dtype: int64

In [53]:
df.dropna()

     A    B    C    D
5  1.0  1.0  1.0  1.0

In [54]:
df.dropna(how="any")

     A    B    C    D
5  1.0  1.0  1.0  1.0

In [55]:
df.dropna(how="any",axis=0) # row

     A    B    C    D
5  1.0  1.0  1.0  1.0

In [56]:
df.dropna(how="any",axis=1) #col

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5]

In [57]:
df.dropna(how="all")

     A    B    C    D
0  1.0  NaN  3.0  4.0
1  2.0  4.0  NaN  8.0
2  NaN  4.0  5.0  9.0
3  NaN  1.0  NaN  3.0
5  1.0  1.0  1.0  1.0

In [58]:
df.dropna(subset=["A"])

     A    B    C    D
0  1.0  NaN  3.0  4.0
1  2.0  4.0  NaN  8.0
5  1.0  1.0  1.0  1.0

In [59]:
df.dropna(how="all",subset=["B","D"]) # any means or, all means and

     A    B    C    D
0  1.0  NaN  3.0  4.0
1  2.0  4.0  NaN  8.0
2  NaN  4.0  5.0  9.0
3  NaN  1.0  NaN  3.0
5  1.0  1.0  1.0  1.0

In [60]:
df.dropna(thresh=2)

     A    B    C    D
0  1.0  NaN  3.0  4.0
1  2.0  4.0  NaN  8.0
2  NaN  4.0  5.0  9.0
3  NaN  1.0  NaN  3.0
5  1.0  1.0  1.0  1.0

In [61]:
df.dropna(thresh=3) # will require 3 filling values 
# =>filling values ; keep in dataframe and delete the remaining rows

     A    B    C    D
0  1.0  NaN  3.0  4.0
1  2.0  4.0  NaN  8.0
2  NaN  4.0  5.0  9.0
5  1.0  1.0  1.0  1.0

In [62]:
df.fillna(df.mean())

          A    B    C    D
0  1.000000  2.5  3.0  4.0
1  2.000000  4.0  3.0  8.0
2  1.333333  4.0  5.0  9.0
3  1.333333  1.0  3.0  3.0
4  1.333333  2.5  3.0  5.0
5  1.000000  1.0  1.0  1.0

In [63]:
df

     A    B    C    D
0  1.0  NaN  3.0  4.0
1  2.0  4.0  NaN  8.0
2  NaN  4.0  5.0  9.0
3  NaN  1.0  NaN  3.0
4  NaN  NaN  NaN  NaN
5  1.0  1.0  1.0  1.0

In [64]:
df["A"]=df["A"].fillna(df['A'].mean())

In [65]:
df

          A    B    C    D
0  1.000000  NaN  3.0  4.0
1  2.000000  4.0  NaN  8.0
2  1.333333  4.0  5.0  9.0
3  1.333333  1.0  NaN  3.0
4  1.333333  NaN  NaN  NaN
5  1.000000  1.0  1.0  1.0