In [67]:
import numpy as np
import pandas as pd

file name -> Columns

quater-i.csv -> ['order_id', 'quantity', 'item_id', 'choice_description_id' 'item_price']

items.csv -> ['item_id', 'item_name']

In [68]:
# import like this
items_path = "items.csv"
q1_path = "quarter-1.csv"
q2_path = "quarter-2.csv"
q3_path = "quarter-3.csv"


q1= pd.read_csv(q1_path)
q2 = pd.read_csv(q2_path)
q3 = pd.read_csv(q3_path)

items = pd.read_csv(items_path)

### `Q:1-5`
1. You are given three quater files, your job is to append these three files and make a single dataframe.
2. Have a index as Q-1 Q-2 Q-3 for respective quater files in the dataframe
3. Your are given a file items.csv which has item_id and item_name. Find out most sold items in each quarter.
4. Find out items which has made most revenue in each quarter.
5. Find out avg order price of each quarter.

***Note: item_price is given as str with $ sign, in earlier task you have converted this to rupees, here too first convert item_price field in rupees.***

In [69]:
q1

      order_id  quantity  item_id  choice_description_id item_price
0            1         1        1                      1     $3.39
1            1         1        2                      2     $3.39
2            2         2        4                      3    $16.98
3            4         1        7                      6     $9.25
4            6         1        9                      8     $8.75
...        ...       ...      ...                    ...        ...
2270      1831         1       16                      0     $1.50
2271      1833         1        6                    276    $11.75
2272      1833         1        6                    904    $11.75
2273      1834         1       20                    303     $8.75
2274      1834         1       20                     30     $8.75

[2275 rows x 5 columns]

In [70]:
q2

      order_id  quantity  item_id  choice_description_id item_price
0            1         1        0                      0     $2.39
1            1         1        3                      0     $2.39
2            3         1        4                      4    $10.98
3            3         1        5                      0     $1.69
4            4         1        6                      5    $11.75
...        ...       ...      ...                    ...        ...
2342      1829         1       23                     92    $11.25
2343      1830         1       23                   1043    $11.25
2344      1832         1       10                    116     $8.75
2345      1832         1        8                      0     $4.45
2346      1834         1       20                    515    $11.25

[2347 rows x 5 columns]

In [71]:
q3

Empty DataFrame
Columns: [order_id, quantity, item_id, choice_description_id, item_price]
Index: []

In [72]:
items

    item_id                              item_name
0         0           Chips and Fresh Tomato Salsa
1         1                                   Izze
2         2                       Nantucket Nectar
3         3  Chips and Tomatillo-Green Chili Salsa
4         4                           Chicken Bowl
5         5                          Side of Chips
6         6                          Steak Burrito
7         7                       Steak Soft Tacos
8         8                    Chips and Guacamole
9         9                   Chicken Crispy Tacos
10       10                     Chicken Soft Tacos
11       11                        Chicken Burrito
12       12                            Canned Soda
13       13                       Barbacoa Burrito
14       14                       Carnitas Burrito
15       15                          Carnitas Bowl
16       16                          Bottled Water
17       17  Chips and Tomatillo Green Chili Salsa
18       18                          Barbacoa Bowl
19       19                                  Chips
20       20                     Chicken Salad Bowl
21       21                             Steak Bowl
22       22                    Barbacoa Soft Tacos
23       23                         Veggie Burrito
24       24                            Veggie Bowl
25       25                     Steak Crispy Tacos
26       26    Chips and Tomatillo Red Chili Salsa
27       27                  Barbacoa Crispy Tacos
28       28                      Veggie Salad Bowl
29       29     Chips and Roasted Chili-Corn Salsa
30       30     Chips and Roasted Chili Corn Salsa
31       31                    Carnitas Soft Tacos
32       32                          Chicken Salad
33       33                      Canned Soft Drink
34       34                       Steak Salad Bowl
35       35                      6 Pack Soft Drink
36       36    Chips and Tomatillo-Red Chili Salsa
37       37                                   Bowl
38       38                                Burrito
39       39                           Crispy Tacos
40       40                  Carnitas Crispy Tacos
41       41                            Steak Salad
42       42      Chips and Mild Fresh Tomato Salsa
43       43                      Veggie Soft Tacos
44       44                    Carnitas Salad Bowl
45       45                    Barbacoa Salad Bowl
46       46                                  Salad
47       47                    Veggie Crispy Tacos
48       48                           Veggie Salad
49       49                         Carnitas Salad

In [73]:
pd.concat((q1,q2,q3))

     order_id quantity item_id choice_description_id item_price
0           1        1       1                     1     $3.39
1           1        1       2                     2     $3.39
2           2        2       4                     3    $16.98
3           4        1       7                     6     $9.25
4           6        1       9                     8     $8.75
...       ...      ...     ...                   ...        ...
2342     1829        1      23                    92    $11.25
2343     1830        1      23                  1043    $11.25
2344     1832        1      10                   116     $8.75
2345     1832        1       8                     0     $4.45
2346     1834        1      20                   515    $11.25

[4622 rows x 5 columns]

In [74]:
#1
df=pd.concat((q1,q2,q3),keys=["Q1","Q2","Q3"])
df

        order_id quantity item_id choice_description_id item_price
Q1 0           1        1       1                     1     $3.39
   1           1        1       2                     2     $3.39
   2           2        2       4                     3    $16.98
   3           4        1       7                     6     $9.25
   4           6        1       9                     8     $8.75
...          ...      ...     ...                   ...        ...
Q2 2342     1829        1      23                    92    $11.25
   2343     1830        1      23                  1043    $11.25
   2344     1832        1      10                   116     $8.75
   2345     1832        1       8                     0     $4.45
   2346     1834        1      20                   515    $11.25

[4622 rows x 5 columns]

In [75]:
#3
df=df.reset_index()
df

,level_0,level_1,order_id,quantity,item_id,choice_description_id,item_price
0,Q1,0,1,1,1,1,$3.39
1,Q1,1,1,1,2,2,$3.39
2,Q1,2,2,2,4,3,$16.98
3,Q1,3,4,1,7,6,$9.25
4,Q1,4,6,1,9,8,$8.75
...,...,...,...,...,...,...,...
4617,Q2,2342,1829,1,23,92,$11.25
4618,Q2,2343,1830,1,23,1043,$11.25
4619,Q2,2344,1832,1,10,116,$8.75
4620,Q2,2345,1832,1,8,0,$4.45
4621,Q2,2346,1834,1,20,515,$11.25

In [76]:
df=df.merge(items,on="item_id")
df[df["item_id"]==4]

,level_0,level_1,order_id,quantity,item_id,choice_description_id,item_price,item_name
47,Q1,2,2,2,4,3,$16.98,Chicken Bowl
48,Q1,6,7,1,4,10,$11.25,Chicken Bowl
49,Q1,12,13,1,4,19,$8.49,Chicken Bowl
50,Q1,21,20,1,4,28,$11.25,Chicken Bowl
51,Q1,39,34,1,4,50,$8.75,Chicken Bowl
...,...,...,...,...,...,...,...,...
768,Q2,2330,1824,1,4,162,$11.25,Chicken Bowl
769,Q2,2331,1825,1,4,276,$11.25,Chicken Bowl
770,Q2,2332,1825,1,4,188,$11.25,Chicken Bowl
771,Q2,2333,1825,1,4,77,$8.75,Chicken Bowl
772,Q2,2337,1826,1,4,1042,$8.75,Chicken Bowl

In [77]:
#3
df.groupby(["level_0","item_name","item_id"],as_index=False)["quantity"].sum()

   level_0              item_name item_id quantity
0       Q1      6 Pack Soft Drink      35       31
1       Q1          Barbacoa Bowl      18       34
2       Q1       Barbacoa Burrito      13       48
3       Q1  Barbacoa Crispy Tacos      27        6
4       Q1    Barbacoa Salad Bowl      45        5
..     ...                    ...     ...      ...
90      Q2         Veggie Burrito      23       45
91      Q2    Veggie Crispy Tacos      47        1
92      Q2           Veggie Salad      48        5
93      Q2      Veggie Salad Bowl      28       10
94      Q2      Veggie Soft Tacos      43        6

[95 rows x 4 columns]

In [78]:
df.groupby(["level_0","item_name"],as_index=False)["quantity"].sum().sort_values("quantity",ascending=False)

   level_0                          item_name quantity
65      Q2                       Chicken Bowl      394
17      Q1                       Chicken Bowl      367
66      Q2                    Chicken Burrito      304
18      Q1                    Chicken Burrito      287
25      Q1                Chips and Guacamole      258
..     ...                                ...      ...
91      Q2                Veggie Crispy Tacos        1
14      Q1                     Carnitas Salad        1
56      Q2                               Bowl        1
46      Q1                       Veggie Salad        1
26      Q1  Chips and Mild Fresh Tomato Salsa        1

[95 rows x 3 columns]

In [81]:
#4
df["price"]=df.item_price.apply(lambda x:float(x[1:]))
df["toal_price"]=df["quantity"]*df["price"]

In [82]:
df.groupby(["level_0","item_name"],as_index=False)["toal_price"].sum().sort_values("toal_price",ascending=False).drop_duplicates("level_0")

   level_0     item_name toal_price
65      Q2  Chicken Bowl    4192.25
17      Q1  Chicken Bowl    3852.38

In [88]:
df.groupby(["level_0","order_id"],as_index=False)["toal_price"].sum().groupby(["level_0"])["toal_price"].mean()

level_0
Q1    13.809488
Q2    13.279828
Name: toal_price, dtype: object

### `Q-6` From the IPL wala dataset you have to find the Purple cap holder each season.

*Note: Bowler with most no wickets in a season gets purple cap. If more than one bowler have same no of wickets in the season, one with least ecomnomy among them is purple cap holder.*

Bowler's Economy = runs-conceded per six ballsum

In [25]:
balls = pd.read_csv("IPL_Ball_by_Ball_2008_2022.csv")
matches = pd.read_csv("IPL_Matches_2008_2022.csv")

Best bowler in death overs.
Note: Have taken most no of wickets in case of tie with least economy

Death Overs - [16-20]

         bowler  IsBowlerWicket  BowlerRun  IsLegalBall   Economy
91     DJ Bravo             115       2161         1385  9.361733
331  SL Malinga             108       1464         1117  7.863921
53      B Kumar              90       1752         1173  8.961637
148   JJ Bumrah              80       1614         1146  8.450262
339   SP Narine              67       1164          949  7.359326

### `Q-8` Batsman record season wise

Make a function which takes a input `batsman_name` and it returns a dataframe.
Columns of the data frame are - `['Season','Innings', 'TotalRuns', 'Avg', 'HighestScore','StrikeRate']`.
* In result make `Season` column as index.

* Avg - total_runs/ no of time got out. - player_out column will help.
* StrikeRate -(total_runs/ balls faced) * 100- wides are not included in batsman ball faced counts. No balls are included. -> Extra_type column will help
* Batsman Can score runs on No Balls.
* Batsman can get out on No Ball or Wides. And even while being on non-striker. Keep these things in mind before masking.

In [11]:
# code here
batterdf = seasondf.copy()
batterdf["IsBatsmanBall"] = batterdf["extra_type"].apply(lambda x: 1 if x != "wides" else 0)

def bat_record_season(batsman):
    bdf = batterdf[batterdf.batter == batsman].copy()
    bdf["IsBatsmanOut"] = bdf.batter == bdf.player_out
    df = bdf.groupby(["Season", "ID"], as_index = False)[["batsman_run", "IsBatsmanBall", "IsBatsmanOut"]].sum()
    innings = df.groupby("Season").ID.count()
    df = df.groupby("Season").agg(
    {
        "batsman_run":["sum", "max"],
        "IsBatsmanBall": "sum",
        "IsBatsmanOut": "sum"
    })
    df["Innings"]= innings
    df["TotalRuns"] = df[("batsman_run", "sum")]
    df["Avg"] = df["TotalRuns"] / df[("IsBatsmanOut", "sum")]
    df["HighestScore"] = df[("batsman_run", "max")]
    df["StrikeRate"] = df["TotalRuns"] / df[("IsBatsmanBall", "sum")] * 100
    return df.drop(columns = ["batsman_run", "IsBatsmanBall", "IsBatsmanOut"])
bat_record_season("MS Dhoni")

        Innings TotalRuns         Avg HighestScore  StrikeRate

Season
2007/08      14       414   41.400000           65  133.548387
2009         13       332   41.500000           58  127.203065
2009/10      11       287   31.888889           66  136.666667
2011         13       392   43.555556           70  158.704453
2012         17       358   32.545455           51  128.776978
2013         16       461   46.100000           67  162.897527
2014         15       371   74.200000           57  148.400000
2015         17       372   31.000000           53  121.967213
2016         12       284   40.571429           64  135.238095
2017         15       290   26.363636           61  116.000000
2018         15       455   75.833333           79  150.662252
2019         12       416  104.000000           84  134.627832
2020/21      12       200   25.000000           47  116.279070
2021         11       114   16.285714           18  106.542056
2022         12       232   33.142857           50  123.404255

### `Q-9` Using both dataset, make a dataframe as described below

Data Frame columns-> `['PlayerOfThematch', 'BattingFigure', 'BowlingFigure']`

* BattingFigure->`<runs>/<balls>`
* BowlingFigure->`<wicket>/<runs-conceded>`

DataFrame should have one record for each match.

Say 'V Kohli' got POM award then in dataset include his batting figure of that match. Say he scored 112runs in 76 balls. And he hasn't bowled so Bowling Figure will be NaN
```
PlayerOfThematch BattingFigure BowlingFigure
V Kohli          112/76         nan  

```

In [12]:
# code here
df = balls.merge(matches[["ID", "Player_of_Match"]], on="ID")
batterdf = df[df.batter == df.Player_of_Match].copy()
batterdf["IsBatsmanBall"] = batterdf["extra_type"].apply(lambda x: 1 if x != "wides" else 0)
batter = batterdf.groupby(["ID", "batter"], as_index=False)[["batsman_run", "IsBatsmanBall"]].sum()
batter["BattingFigure"] = batter[["batsman_run", "IsBatsmanBall"]].apply(lambda x: '/'.join(map(str, x.values)), axis = 1)
batter.rename(columns = {"batter": "PlayerOfMatch"}, inplace = True)
batter.head()

       ID PlayerOfMatch  batsman_run  IsBatsmanBall BattingFigure
0  335982   BB McCullum          158             73        158/73
1  335983    MEK Hussey          116             54        116/54
2  335985    MV Boucher           39             19         39/19
3  335986     DJ Hussey           38             43         38/43
4  335987     SR Watson           76             49         76/49

In [13]:
bowlerdf = df[df.bowler == df.Player_of_Match].copy()
bowlerdf["IsBowlerWicket"] = bowlerdf["kind"].apply(lambda x: 1 if x in ["caught", 'caught and bowled', 'bowled', 'stumped','lbw', 'hit wicket'] else 0)
bowlerdf["BowlerRun"] = bowlerdf.extra_type.apply(lambda x: 0 if x in ["legbyes", "byes"] else 1) * bowlerdf["total_run"]
bowler = bowlerdf.groupby(["ID", "bowler"], as_index=False)[["IsBowlerWicket", "BowlerRun"]].sum()
bowler["BowlingFigure"] = bowler[["IsBowlerWicket", "BowlerRun"]].apply(lambda x: '/'.join(map(str, x.values)), axis = 1)
bowler.rename(columns = {"bowler": "PlayerOfMatch"}, inplace = True)
bowler.head()

       ID PlayerOfMatch  IsBowlerWicket  BowlerRun BowlingFigure
0  335984   MF Maharoof               2         11          2/11
1  335986     DJ Hussey               1         35          1/35
2  335987     SR Watson               0         39          0/39
3  335990     YK Pathan               2         20          2/20
4  335992     SR Watson               2         20          2/20

In [14]:
batter.merge(bowler, on=["ID", "PlayerOfMatch"], how = "outer").drop(columns = ["batsman_run", "IsBatsmanBall", "IsBowlerWicket", "BowlerRun"]).head()

       ID PlayerOfMatch BattingFigure BowlingFigure
0  335982   BB McCullum        158/73           NaN
1  335983    MEK Hussey        116/54           NaN
2  335984   MF Maharoof           NaN          2/11
3  335985    MV Boucher         39/19           NaN
4  335986     DJ Hussey         38/43          1/35